### ISSUE TITLE
Logo / name

### ISSUE THREAD

**Issue by will-stone** [Vorror/Objektiv#2]
Came here after seeing that Objecktiv was dead. Great work! A new name would be good, so people find this instead of the abandoned project. May I suggest, as a nod to the original, "Subjektiv"?

**Comment by xuv** [comment]
Based on @cmeury’s observation in issue #4 and the impossibility to bring this app into Homebrew because of a name conflict. It sounds like it’s the right time to rename this app to @will-stone proposition. And re-open this issue.

**Comment by will-stone** [comment]
I totally forgot about this. It was partly inspiration for me creating [Browserosaurus](https://browserosaurus.com/) 🙂

Doesn't look like this project is being worked on either (last commit on 11 Jan 2017), I would suggest another fork if people want to keep it going.

**Comment by cmeury** [comment]
Didn't know abut Browserosaurus. That one can be installed already via homebrew: `brew cask install browserosaurus`.

@will-stone If Browserosaurus would support switching the default browser instead of prompting, it would completely replace Objektiv and we could put this issue to rest.

**Comment by Vorror** [comment]
👋 I've been inactive here and I'm sorry about that.

@cmeury I too would probably recommend Browserosaurus. Especially since it's free + actively being developed. I too may switch at some point. My goal for Objektiv was mainly to fix any outstanding issues.

**Comment by cmeury** [comment]
@Vorror After trying out both applications I'm kinda leaning back towards Objektiv -- it's the simpler tool that directly solves my problem. I wouldn't be against re-starting this tool as a fresh project under a new name, using and crediting this existing source code. Looks like the [license](https://tldrlegal.com/license/mit-license#summary) allows this. I'd offer to assist with finding a new name, setting things up & maintaining. I have no experience with the language used, but with software development in general. And if you're not that keen on it, I can also create it over on my account. Let me know what you think.

**Comment by cmeury** [comment]
Good news folks, the developer `anks` added me as a maintainer of the original repository. I'll see that I can make the binary available again and please create a PR with your fixes @Vorror :)

**Comment by xuv** [comment]
@cmeury Wow. That’s absolutely stellar news. Great job on following up on that.

**Comment by Vorror** [comment]
@cmeury I'll get on it over the weekend :)

**Comment by Vorror** [comment]
@cmeury I know it's not best practice, but would you mind if I create a PR from Master(mine) -> Master(upstream)? If so, I can create a PR immediately. The only change that would need to be done after is changing the download url in the readme.

**Comment by cmeury** [comment]
I think it's fine to get things working again quickly. I managed to build the project locally, but not sure which binary to take, or if I need to specify some form of "release" mode. As said, I'm unfamiliar with Xcode development :) How do you usually create the ZIP file for release?

**Comment by Vorror** [comment]
@cmeury Do you mind if I send you an email about it over the weekend(the one listed in your GH profile)? I want to check out the project again and make sure I give you the right info.

**Comment by cmeury** [comment]
You're welcome to send me a mail. 

As for 0.6.3, I'll just enter that exact commit and tag in the main repo together with the binary from your fork, so we're up to the current state of things. Then we can do one or more PRs with some polish to do a 0.6.4 -- how does that sound?

**Comment by Vorror** [comment]
@cmeury Sounds good to me
