### ISSUE TITLE
Feature request: option to choose browser on-the-fly

### ISSUE THREAD

**Issue by will-stone** [Vorror/Objektiv#3]
I'd like to suggest a new feature; when a user clicks a link in an app, prompt which browser to use.
I see you've gotten around the default browser prompt by setting Objektiv as the default browser. From here, is it fairly easy to stop passing the link through to the "fake" default browser and instead wait for the user to choose a browser to send the link to using the overlay menu?

**Comment by will-stone** [comment]
Just clearing-up some old issues of mine. I implemented the behaviour I required by writing my own app, [Browserosaurus](https://browserosaurus.com/).

**Comment by Soneji** [comment]
Hi @will-stone 

That seems to be a dead link. Do you have another link and are you still supporting browserosaurus as I am also looking for that feature

**Comment by Soneji** [comment]
Oh nevermind I found it. It is amazing by the way. Thank you

**Comment by will-stone** [comment]
@overclockedllama I've updated the link. Thanks 😄
